# Generated by Django 3.2.9 on 2022-02-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='news',
        ),
    ]
