# Generated by Django 3.2.9 on 2021-12-02 09:25

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.change_name2, verbose_name='عکس')),
                ('description', models.TextField()),
                ('information', models.TextField()),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('Number', models.IntegerField()),
            ],
        ),
    ]
