# Generated by Django 3.2.9 on 2022-01-25 06:14

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_sold_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=product.models.change_name2, verbose_name='عکس'),
        ),
    ]
