# Generated by Django 3.2.9 on 2022-01-30 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_gallery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
