# Generated by Django 3.2.9 on 2022-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_tag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
