# Generated by Django 3.2.9 on 2022-02-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20220215_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
