# Generated by Django 3.2.9 on 2021-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211220_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='discount_number',
            field=models.FloatField(null=True),
        ),
    ]
