# Generated by Django 3.2.9 on 2021-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_discountcode_discount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_number',
            field=models.IntegerField(null=True),
        ),
    ]
