# Generated by Django 3.2.9 on 2021-12-20 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_discountcode_discount_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='expir_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
