# Generated by Django 3.2.9 on 2021-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_discountcode_expir_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
