# Generated by Django 3.2.9 on 2021-12-21 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_discountcode_discount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
